### ISSUE TITLE
NekoDA file empty

### ISSUE THREAD

**Issue by TheLastZombie** [eliot-akira/neko#2]
The [archived version of NekoDA](https://github.com/eliot-akira/neko/blob/main/1989-macintosh-neko-da/neko) is 0 bytes in size.

I followed the [Internet Archive link](https://web.archive.org/web/20090728135047/http://geocities.com/neko_mac/) in the README and downloaded the SIT file myself, and sure enough, after extraction all that remains is an empty file.

I don't know why this happens – my only guess is that the SIT format has evolved over the years, and today's software is simply unable to extract the relatively old archive – but I thought I'd let you know anyway.

**Comment by eliot-akira** [comment]
Thanks for letting me know! I found some old StuffIt archives for NekoDA, so I've added them to the folder instead: https://github.com/eliot-akira/neko/tree/main/1989-macintosh-neko-da

Recently I'm trying to get Mini vMac emulator running in a browser, based on [minivmac-em](https://github.com/yksoft1/minivmac-em). That would be cool if I could figure out a way to extract the real `neko` binary and run it. It might already be possible with [minivmac](https://www.gryphel.com/c/minivmac/index.html) itself.
